version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=expenses_docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=AAy789
  web:
    build: .
    command: python run.py -i -w
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  postgres_data: